server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: Notification
          uri: http://localhost:8081
          predicates:
            - Path=/notices/** 
        - id: Member
          uri: http://localhost:8082
          predicates:
            - Path=/members/** 
        - id: Payment
          uri: http://localhost:8083
          predicates:
            - Path=/payments/** 
        - id: Reservation
          uri: http://localhost:8084
          predicates:
            - Path=/reservations/**, /biddings/** 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: Notification
          uri: http://notification:8080
          predicates:
            - Path=/notices/** 
        - id: Member
          uri: http://member:8080
          predicates:
            - Path=/members/** 
        - id: Payment
          uri: http://payment:8080
          predicates:
            - Path=/payments/** 
        - id: Reservation
          uri: http://reservation:8080
          predicates:
            - Path=/reservations/**, /biddings/** 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
